# 3-class
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2 --experiment_name DenseNet121_320_1e-04_uncertainty_3-class_top10 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True --model_uncertainty=True && \
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2 --experiment_name DenseNet121_320_1e-04_uncertainty_3-class_top10_2 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True --model_uncertainty=True && \
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2,3 --experiment_name DenseNet121_320_1e-04_uncertainty_3-class_top10_3 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True --model_uncertainty=True

# Ignore
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2 --experiment_name DenseNet121_320_1e-04_uncertainty_ignore_top10 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True && \
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2 --experiment_name DenseNet121_320_1e-04_uncertainty_ignore_top10_2 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True && \
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2,3 --experiment_name DenseNet121_320_1e-04_uncertainty_ignore_top10_3 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True

# Self-Train
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2 --experiment_name DenseNet121_320_1e-04_uncertainty_self-train_top10 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True --uncertain_map_path=uncertainty_self-train.csv && \
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2 --experiment_name DenseNet121_320_1e-04_uncertainty_self-train_top10_2 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True --uncertain_map_path=uncertainty_self-train.csv && \
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2,3 --experiment_name DenseNet121_320_1e-04_uncertainty_self-train_top10_3 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True --uncertain_map_path=uncertainty_self-train.csv

# Ones
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2 --experiment_name DenseNet121_320_1e-04_uncertainty_ones_top10 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True --uncertain_map_path=uncertainty_ones.csv && \
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2 --experiment_name DenseNet121_320_1e-04_uncertainty_ones_top10_2 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True --uncertain_map_path=uncertainty_ones.csv && \
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2,3 --experiment_name DenseNet121_320_1e-04_uncertainty_ones_top10_3 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True --uncertain_map_path=uncertainty_ones.csv

# Zeros
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2 --experiment_name DenseNet121_320_1e-04_uncertainty_zeros_top10 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True --uncertain_map_path=uncertainty_zeros.csv && \
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2 --experiment_name DenseNet121_320_1e-04_uncertainty_zeros_top10_2 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True --uncertain_map_path=uncertainty_zeros.csv && \
python train.py --dataset chexpert --batch_size 48 --iters_per_print 48 --iters_per_visual 48000 --iters_per_eval=4800 --iters_per_save=4800 --gpu_ids 0,1,2,3 --experiment_name DenseNet121_320_1e-04_uncertainty_zeros_top10_3 --num_epochs=3 --metric_name chexpert-competition-AUROC --maximize_metric True --scale 320 --save_dir /deep/group/CheXpert/final_ckpts --max_ckpts 10 --keep_topk True --uncertain_map_path=uncertainty_zeros.csv